export const ADD_INCOME_ITEM = "ADD_INCOME_ITEM";
export const ADD_FUNDS_ITEM = "ADD_FUNDS_ITEM";
export const ADD_EXPENCES_ITEM = "ADD_EXPENCES_ITEM";
export const TOGGLE_BURGER_MENU = "TOGGLE_BURGER_MENU";
export const GET_TODAY_CURRENCY_RATE = "GET_TODAY_CURRENCY_RATE";
